# Generated by Django 3.0.5 on 2020-05-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('unique_Squirrel_ID', models.CharField(max_length=50, verbose_name='Unique_Squirrel_ID')),
                ('shift', models.CharField(choices=[('am', 'AM'), ('pm', 'PM')], max_length=50, verbose_name='Shift')),
                ('date', models.DateField(verbose_name='Date')),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], max_length=50, verbose_name='Age')),
            ],
        ),
    ]
